### ISSUE TITLE
Authorisation Functionality

### ISSUE THREAD

**Issue by Mixerou** [Mixerou/contrel#1]
### TODO List

- Backend
  - [x] Create `/register` endpoint
  - [x] Create `/login` endpoint
  - [x] Create `/logout` endpoint
- Desktop Client
  - [x] Create `auth` layout and `auth` screen
  - [x] Create logout functionality
  - [x] Connect to the backend
